name: "Security checks"

on:
  push:
    branches: [main]
    paths:
      - '**.go'
      - 'Makefile'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/test-unit.yml'
  pull_request:
    branches: [main]
    paths:
      - '**.go'
      - 'Makefile'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/test-unit.yml'

jobs:
  security-checks:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v3
      - name: Run golang ci lint for security
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout 3m0s -E gosec
